name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: ./mvnw package

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cubix-cloudnative-block1-homework .
          docker push ${{ secrets.DOCKER_USERNAME }}/cubix-cloudnative-block1-homework

  verify:
    name: Verify Docker Image
    runs-on: ubuntu-latest

    needs: publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify Docker Image
        run: bash verify-image.sh
